version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: boto3
    versions:
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.30
    - 1.17.31
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.37
    - 1.17.38
    - 1.17.39
    - 1.17.40
    - 1.17.41
    - 1.17.42
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.60
  - dependency-name: fcm-django
    versions:
    - 0.3.8
  - dependency-name: django
    versions:
    - 3.1.7
    - 3.1.8
  - dependency-name: django-extensions
    versions:
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: cryptography
    versions:
    - 3.4.6
  - dependency-name: pillow
    versions:
    - 8.1.2
  commit-message:
    prefix: Crowdbotics
